Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
import pandas as pd
import numpy as np 
from sklearn.datasets import load_iris

#1. Extract feature matrix as NumPy array
iris_dataset = load_iris()
print ("Iris Feature matrix as NumPy array (displaying first 10 rows):")
print (iris_dataset.data[:10])
#2. Compute:
#Mean
#Median
#Standard deviation
#Variance (for each feature)
mean = np.mean(iris_dataset.data, axis=0)
median = np.median(iris_dataset.data, axis=0)
std_dev = np.std(iris_dataset.data, axis=0)
variance = np.var(iris_dataset.data, axis=0)
print("\nMean of each feature:")
print(mean)
print("\nMedian of each feature:")
print(median)
print("\nStandard Deviation of each feature:")
print(std_dev)
print("\nVariance of each feature:")
print(variance)
#3. Identify:Which feature has highest variability and why it matters in ML
high_var_feature_index = np.argmax(variance)
iris_feature = iris_dataset.feature_names
high_var_feature = iris_feature[high_var_feature_index]
print(f"\nFeature with the highest variability is {high_var_feature} with Variance: {variance[high_var_feature_index]:.4f}.")
print("\nWhy it matters in ML?")
print('''Features that change more across data points can help the model identify patterns and differences.
If the variation is related to the target, it improves prediction.
Features with very low variability usually add little value and can be ignored.''')


Iris Feature matrix as NumPy array (displaying first 10 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Mean of each feature:
[5.84333333 3.05733333 3.758      1.19933333]

Median of each feature:
[5.8  3.   4.35 1.3 ]

Standard Deviation of each feature:
[0.82530129 0.43441097 1.75940407 0.75969263]

Variance of each feature:
[0.68112222 0.18871289 3.09550267 0.57713289]

Feature with the highest variability is petal length (cm) with Variance: 3.0955.

Why it matters in ML?
Features that change more across data points can help the model identify patterns and differences.
If the variation is related to the target, it improves prediction.
Features with very low variability usually add little value and can be ignored.


Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [2]:
import pandas as pd
import seaborn as sns

iris_df = sns.load_dataset('iris')
#iris_df.head()
#1. Extract:First 100 samples Only last 2 features
last_2_features = iris_df.iloc[:100,-2:]
print("First 100 samples with only the last 2 features:")
print(last_2_features)
#2. Use boolean masking:Select samples where petal length is greater than dataset mean
#iris_df.head()
#iris_df.describe()
avg_petal_length = iris_df['petal_length'].mean()
filtered_samples = iris_df[iris_df['petal_length'] > avg_petal_length]
print("Samples with petal length greater than the mean:")
print(filtered_samples)
#3. Count selected samples
count = filtered_samples.shape[0]
print(f"Number of samples with petal length greater than the average petal length: {count}.")
#4. Explain how this relates to feature-based filtering in ML
print("\nExplain how this relates to feature-based filtering in ML:")
print('''Feature-based filtering uses specific features to select relevant samples for training.
By filtering samples where petal_length > mean, we focused on a meaningful subset and removed noise.
This helps the model concentrate on patterns that matter, improving accuracy and reducing overfitting.
In real ML, this type of filtering creates cleaner, more focused datasets for better model performance.''')





First 100 samples with only the last 2 features:
    petal_width     species
0           0.2      setosa
1           0.2      setosa
2           0.2      setosa
3           0.2      setosa
4           0.2      setosa
..          ...         ...
95          1.2  versicolor
96          1.3  versicolor
97          1.3  versicolor
98          1.1  versicolor
99          1.3  versicolor

[100 rows x 2 columns]
Samples with petal length greater than the mean:
     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2        

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [3]:
import numpy as np
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()
X = iris.data

# 1. Apply standardization: X' = (X - μ) / σ
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std

print("Original data (first 5 rows):")
print(X[:5])
print("\nStandardized data (first 5 rows):")
print(X_standardized[:5])

# 2. Verify: Mean ≈ 0, Std ≈ 1
mean_standardized = np.mean(X_standardized, axis=0)
std_standardized = np.std(X_standardized, axis=0)

np.set_printoptions(precision=6, suppress=True)

print("\nVerification after standardization:")
print("Mean of each feature:", mean_standardized)
print("Std of each feature:", std_standardized)


Original data (first 5 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Standardized data (first 5 rows):
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

Verification after standardization:
Mean of each feature: [-0. -0. -0. -0.]
Std of each feature: [1. 1. 1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [ ]:
import pandas as pd
import seaborn as sns

# Load the Titanic dataset
titanic = sns.load_dataset('titanic')

# 1. Let's look at the data
print("First few rows:")
print(titanic.head())
print("\nLast few rows:")
print(titanic.tail())

# Check the info
print("\nInfo about the dataset:")
titanic.info()

# Summary stats
print("\nBasic statistics:")
print(titanic.describe())

# 2. Missing values and feature types
print("\n" + "="*40)
print("Missing values:")
print(titanic.isnull().sum())

print("\nData types:")
print(titanic.dtypes)

# 3. Why this matters
print("\n" + "="*40)
print("Why identify feature types?")
print("- Numbers can go directly to the model")
print("- Text needs to be converted to numerics first")
print("- Missing data needs different fixes based on type")
print("- Some models only work with numbers, so we need to know what we're dealing with")

First few rows:
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

Last few rows:
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [5]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

# 1. Filter for female passengers in 1st class
female_first_class = titanic[(titanic['sex'] == 'female') & (titanic['pclass'] == 1)]
print("Female passengers in 1st class:")
print(female_first_class.head())

# 2. Survival rate for this group
survival_rate_female_first = female_first_class['survived'].mean()
print(f"\nSurvival rate for female passengers in 1st class: {survival_rate_female_first:.2%}")

# 3. Overall survival rate
overall_survival = titanic['survived'].mean()
print(f"Overall survival rate: {overall_survival:.2%}")

# 4. What does this tell us?
print("\n" + "="*50)
print("Insight for feature engineering:")
print(f"Female 1st class had survival rate: {survival_rate_female_first:.2%}")
print(f"Overall had: {overall_survival:.2%}")
print(f"Difference: {(survival_rate_female_first - overall_survival):.2%}")
print("\nThis shows that being female AND in 1st class really helped survival.")
print("So combining sex + class as a feature might be useful for the model.")

Female passengers in 1st class:
    survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1          1       1  female  38.0      1      0   71.2833        C  First   
3          1       1  female  35.0      1      0   53.1000        S  First   
11         1       1  female  58.0      0      0   26.5500        S  First   
31         1       1  female   NaN      1      0  146.5208        C  First   
52         1       1  female  49.0      1      0   76.7292        C  First   

      who  adult_male deck  embark_town alive  alone  
1   woman       False    C    Cherbourg   yes  False  
3   woman       False    C  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
31  woman       False    B    Cherbourg   yes  False  
52  woman       False    D    Cherbourg   yes  False  

Survival rate for female passengers in 1st class: 96.81%
Overall survival rate: 38.38%

Insight for feature engineering:
Female 1st class had survival rate: 96.81%
Over

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [7]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

# First check what's missing
print("Missing values before cleaning:")
print(titanic.isnull().sum())

# 1. Fill missing age with median
age_median = titanic['age'].median()
print(f"\nMedian age: {age_median}")
titanic['age'] = titanic['age'].fillna(age_median)

# 2. Fill missing embarked with mode (most common value)
embarked_mode = titanic['embarked'].mode()[0]
print(f"Most common embark port: {embarked_mode}")
titanic['embarked'] = titanic['embarked'].fillna(embarked_mode)

# 3. Drop the deck column (has too many missing values)
titanic.drop('deck', axis=1, inplace=True)

print("\nMissing values after cleaning:")
print(titanic.isnull().sum())

# 4. Why different strategies?
print("\n" + "="*50)
print("Why use different strategies?")
print("\nAge: Used median because it's a number")
print("- We can't use a category for age")
print("- Median is better than mean (less affected by outliers)")
print("\nEmbarked: Used mode because it's a category")
print("- Can't use a number for a port name")
print("- Mode picks the most common port")
print("\nDeck: Just dropped it")
print("- Too many missing values (too incomplete)")
print("- Not worth trying to fix")

Missing values before cleaning:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Median age: 28.0
Most common embark port: S

Missing values after cleaning:
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

Why use different strategies?

Age: Used median because it's a number
- We can't use a category for age
- Median is better than mean (less affected by outliers)

Embarked: Used mode because it's a category
- Can't use a number for a port name
- Mode picks the most common port

Deck: Just dropped it
- Too many missing values (too incomplete

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [9]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

# 1. Create family_size
titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1 #themselves
print("Created family_size:")
print(titanic[['sibsp', 'parch', 'family_size']].head(10))

# 2. Create is_alone (1 if family_size is 1, else 0)
titanic['is_alone'] = (titanic['family_size'] == 1).astype(int)
print("\nCreated is_alone:")
print(titanic[['family_size', 'is_alone']].head(10))

# 3. Survival rate by is_alone
print("\n" + "="*50)
print("Survival rates:")
survival_by_alone = titanic.groupby('is_alone')['survived'].mean()
print(survival_by_alone)
print(f"\nAlone passengers survived: {survival_by_alone[1]:.2%}")
print(f"Not alone passengers survived: {survival_by_alone[0]:.2%}")

# 4. Why does this help?
print("\n" + "="*50)
print("Why these features help:")
print("- family_size tells the model how many people traveled together")
print("- is_alone is simpler - just 0 or 1")
print("- The model can learn that people traveling alone had different survival rates")
print("- These are easier for the model to use than sibsp and parch separately")
print("- Sometimes combining info creates better patterns for the model to learn")

Created family_size:
   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1
5      0      0            1
6      0      0            1
7      3      1            5
8      0      2            3
9      1      0            2

Created is_alone:
   family_size  is_alone
0            2         0
1            2         0
2            1         1
3            2         0
4            1         1
5            1         1
6            1         1
7            5         0
8            3         0
9            2         0

Survival rates:
is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64

Alone passengers survived: 30.35%
Not alone passengers survived: 50.56%

Why these features help:
- family_size tells the model how many people traveled together
- is_alone is simpler - just 0 or 1
- The model can learn that people traveling alone had different survival rates
- T

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [11]:
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

# 1. Average tip by day
print("Average tip by day:")
avg_tip_by_day = tips.groupby('day', observed=True)['tip'].mean()
print(avg_tip_by_day)

# Total bill by gender
print("\nTotal bill by gender:")
total_bill_by_gender = tips.groupby('sex', observed=True)['total_bill'].sum()
print(total_bill_by_gender)

# 2. Create tip_percentage
tips['tip_percentage'] = (tips['tip'] / tips['total_bill']) * 100
print("\nTip percentage (first 5 rows):")
print(tips[['total_bill', 'tip', 'tip_percentage']].head())

# 3. Which day has highest tipping
print("\n" + "="*50)
avg_tip_pct_by_day = tips.groupby('day', observed=True)['tip_percentage'].mean()
print("Average tip percentage by day:")
print(avg_tip_pct_by_day)
highest_tipping_day = avg_tip_pct_by_day.idxmax()
print(f"\nHighest tipping day: {highest_tipping_day} ({avg_tip_pct_by_day[highest_tipping_day]:.1f}%)")

# 4. How does this help segmentation?
print("\n" + "="*50)
print("How this helps in segmentation:")
print("- We can split customers into groups (by day, gender, etc)")
print("- Saturdays and Sundays might be different from weekdays")
print("- Males and females might tip differently")
print("- If we know these patterns, we can predict who tips more")
print("- The model can learn: 'customers on Saturday tip better'")
print("- We can target different strategies for different segments")

Average tip by day:
day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

Total bill by gender:
sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

Tip percentage (first 5 rows):
   total_bill   tip  tip_percentage
0       16.99  1.01        5.944673
1       10.34  1.66       16.054159
2       21.01  3.50       16.658734
3       23.68  3.31       13.978041
4       24.59  3.61       14.680765

Average tip percentage by day:
day
Thur    16.127563
Fri     16.991303
Sat     15.315172
Sun     16.689729
Name: tip_percentage, dtype: float64

Highest tipping day: Fri (17.0%)

How this helps in segmentation:
- We can split customers into groups (by day, gender, etc)
- Saturdays and Sundays might be different from weekdays
- Males and females might tip differently
- If we know these patterns, we can predict who tips more
- The model can learn: 'customers on Saturday tip better'
- We can target different strategies for different s

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [12]:
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

# 1. Filter: total_bill > 20 AND tip < 3
filtered = tips[(tips['total_bill'] > 20) & (tips['tip'] < 3)]
print("Filtered data (high bill, low tip):")
print(filtered)

# 2. Select only relevant columns
relevant = filtered[['total_bill', 'tip', 'day', 'sex', 'size']]
print("\nRelevant columns only:")
print(relevant)

# 3. Analyze - is this segment under-tipping?
print("\n" + "="*50)
print("Analysis:")
print(f"Count: {len(filtered)} cases")
print(f"Average bill: ${filtered['total_bill'].mean():.2f}")
print(f"Average tip: ${filtered['tip'].mean():.2f}")

overall_avg_tip_pct = (tips['tip'].sum() / tips['total_bill'].sum()) * 100
filtered_tip_pct = (filtered['tip'].sum() / filtered['total_bill'].sum()) * 100
print(f"\nOverall tip percentage: {overall_avg_tip_pct:.1f}%")
print(f"This segment's tip percentage: {filtered_tip_pct:.1f}%")
print("\nYes, they're definitely under-tipping!")

# 4. How does this help anomaly detection?
print("\n" + "="*50)
print("How filtering helps detect anomalies:")
print("- We found a small group with weird behavior (high bill + low tip)")
print("- This is suspicious - might be complaints or errors")
print("- We can flag these for review")
print("- The model learns: this pattern is different from normal")
print("- Real-world use: find fraud, mistakes, or unhappy customers")
print("- Filter first, then investigate the outliers")

Filtered data (high bill, low tip):
     total_bill   tip     sex smoker   day    time  size
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
48        28.55  2.05    Male     No   Sun  Dinner     3
57        26.41  1.50  Female     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
166       20.76  2.24    Male     No   Sun  Dinner     2
187       30.46  2.00    Male    Yes   Sun  Dinner     5
192       28.44  2.56    Male    Yes  Thur   Lunch     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
210       30.06  2.00    Male    Yes   Sat  Dinner  

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [13]:
import numpy as np

# 1. Create two arrays of shape (3,2)
arr1 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

# 2. Vertical stacking (stack on top of each other)
v_stacked = np.vstack([arr1, arr2])
print("\n" + "="*50)
print("Vertical stacking (vstack):")
print(v_stacked)
print(f"Shape: {v_stacked.shape}")

# Horizontal stacking (stack side by side)
h_stacked = np.hstack([arr1, arr2])
print("\nHorizontal stacking (hstack):")
print(h_stacked)
print(f"Shape: {h_stacked.shape}")

# 3. Reshape into (2,6)
print("\n" + "="*50)
reshaped = v_stacked.reshape(2, 6)
print("Reshaped to (2,6):")
print(reshaped)
print(f"Shape: {reshaped.shape}")

# 4. Why reshaping matters
print("\n" + "="*50)
print("Why reshaping is important:")
print("- Models expect data in specific shapes")
print("- If you have 12 values but need (2,6), you reshape")
print("- Changing from (6,2) to (2,6) rearranges the same data")
print("- It's like reorganizing rows and columns")
print("- Most models need data as (samples, features)")
print("- If your data is the wrong shape, the model won't work")

Array 1:
[[1 2]
 [3 4]
 [5 6]]

Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Vertical stacking (vstack):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape: (6, 2)

Horizontal stacking (hstack):
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
Shape: (3, 4)

Reshaped to (2,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)

Why reshaping is important:
- Models expect data in specific shapes
- If you have 12 values but need (2,6), you reshape
- Changing from (6,2) to (2,6) rearranges the same data
- It's like reorganizing rows and columns
- Most models need data as (samples, features)
- If your data is the wrong shape, the model won't work


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import seaborn as sns

# 1. Load dataset
titanic = sns.load_dataset('titanic')
print("Dataset loaded:", titanic.shape)

# 2. Handle missing values
titanic['age'] = titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])
titanic.drop('deck', axis=1, inplace=True)
print("Missing values handled")

# 3. Encode categorical variables
# Sex: male/female to 1/0
titanic['sex'] = (titanic['sex'] == 'male').astype(int)

# Embarked: C/Q/S to 0/1/2
embarked_map = {'C': 0, 'Q': 1, 'S': 2}
titanic['embarked'] = titanic['embarked'].map(embarked_map)
print("Categorical variables encoded")

# 4. Select features and normalize
features = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']
X = titanic[features]

scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)
print("Features normalized")

# 5. Convert to NumPy array and show result
print(f"\nFinal feature matrix shape: {X_normalized.shape}")
print("First 5 rows:")
print(X_normalized[:5])

Dataset loaded: (891, 15)
Missing values handled
Categorical variables encoded
Features normalized

Final feature matrix shape: (891, 7)
First 5 rows:
[[ 0.827377  0.737695 -0.565736  0.432793 -0.473674 -0.502445  0.585954]
 [-1.566107 -1.355574  0.663861  0.432793 -0.473674  0.786845 -1.942303]
 [ 0.827377 -1.355574 -0.258337 -0.474545 -0.473674 -0.488854  0.585954]
 [-1.566107 -1.355574  0.433312  0.432793 -0.473674  0.42073   0.585954]
 [ 0.827377  0.737695  0.433312 -0.474545 -0.473674 -0.486337  0.585954]]


Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [18]:
import pandas as pd
import seaborn as sns

# Load iris data
tips = sns.load_dataset('iris')

# 1. Compute correlation matrix using only numeric columns
corr_matrix = tips.corr(numeric_only=True)
print("Correlation matrix:")
print(corr_matrix)

# 2. Identify highly correlated features
# We consider absolute correlation > 0.8 as high.
high_corr = corr_matrix.abs() > 0.8
print("\nHighly correlated pairs (abs value > 0.8):")
print(high_corr)

# 3. Drop redundant features
# Petal length and petal width are usually very correlated with sepal measurements.
# Let's keep the two clearest features and drop one redundant one.
selected_features = tips[['sepal_length', 'sepal_width', 'petal_length']]
print("\nSelected features after dropping a redundant one:")
print(selected_features.head())

# 4. Explain impact on overfitting and model performance
print("\nWhy drop redundant features?")
print("- Redundant features add noise without giving new information.")
print("- Fewer features reduce the chance of overfitting.")
print("- Models train faster with fewer columns.")
print("- If two columns tell the same story, keeping both does not help much.")
print("- Good feature selection makes the model simpler and more stable.")

Correlation matrix:
              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

Highly correlated pairs (abs value > 0.8):
              sepal_length  sepal_width  petal_length  petal_width
sepal_length          True        False          True         True
sepal_width          False         True         False        False
petal_length          True        False          True         True
petal_width           True        False          True         True

Selected features after dropping a redundant one:
   sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [20]:
import pandas as pd
import seaborn as sns

# Load Titanic dataset
titanic = sns.load_dataset('titanic')

# 1. Create age_group using apply()
def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

# Fill missing age first so apply() works without errors
titanic['age'] = titanic['age'].fillna(titanic['age'].median())
titanic['age_group'] = titanic['age'].apply(age_group)

# 2. Show the new column
def print_group_sample():
    print(titanic[['age', 'age_group']].head(10))

print_group_sample()

# 3. Compute survival rate per group
survival_by_age_group = titanic.groupby('age_group')['survived'].mean()
print('\nSurvival rate by age group:')
print(survival_by_age_group)

# 4. Interpret the result
best_group = survival_by_age_group.idxmax()
print(f"\nHighest survival likelihood: {best_group}")
print('\nWhat this means:')
print('- We grouped passengers into Child, Adult, Senior')
print('- Then we checked who survived most often in each group')
print('- The group with the highest rate is the safest segment')
print('- This helps the model know which age category matters most')

    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child

Survival rate by age group:
age_group
Adult     0.364362
Child     0.539823
Senior    0.269231
Name: survived, dtype: float64

Highest survival likelihood: Child

What this means:
- We grouped passengers into Child, Adult, Senior
- Then we checked who survived most often in each group
- The group with the highest rate is the safest segment
- This helps the model know which age category matters most


Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [21]:
import numpy as np

# 1. Generate 1000 random error values using NumPy
errors = np.random.normal(loc=0, scale=1, size=1000)

# 2. Compute mean and standard deviation
mean_error = np.mean(errors)
std_error = np.std(errors)
print(f"Mean error: {mean_error:.4f}")
print(f"Standard deviation: {std_error:.4f}")

# 3. Identify outliers using mean ± 2*std
lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error
outliers = errors[(errors < lower_bound) | (errors > upper_bound)]

print(f"\nOutliers count: {len(outliers)}")
print("Example outliers:")
print(outliers[:10])

# 4. Explain what high variance means in model performance
print("\nWhy high variance matters:")
print("- High variance means errors are spread out a lot.")
print("- The model is not consistent; sometimes it makes small errors, sometimes large ones.")
print("- This is bad because it means the model is unreliable on new data.")
print("- In ML, lower variance usually means more stable predictions.")

Mean error: -0.0247
Standard deviation: 1.0094

Outliers count: 40
Example outliers:
[ 2.620373 -2.286343  3.497912 -2.659714 -2.458386  2.384962 -2.336618
 -2.157185  2.172923 -2.104163]

Why high variance matters:
- High variance means errors are spread out a lot.
- The model is not consistent; sometimes it makes small errors, sometimes large ones.
- This is bad because it means the model is unreliable on new data.
- In ML, lower variance usually means more stable predictions.


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [22]:
import pandas as pd
import seaborn as sns

# Load tips dataset
tips = sns.load_dataset('tips')

# 1. Create tip_percentage
tips['tip_percentage'] = (tips['tip'] / tips['total_bill']) * 100

# 2. Group by day and time
summary = tips.groupby(['day', 'time'], observed=True).agg(
    total_revenue=('total_bill', 'sum'),
    avg_tip_percentage=('tip_percentage', 'mean'),
    count=('tip', 'size')
).reset_index()

print('Revenue summary by day and time:')
print(summary)

# 3. Identify highest revenue segment
best_segment = summary.loc[summary['total_revenue'].idxmax()]
print('\nHighest revenue segment:')
print(best_segment)

# 4. Recommendation and ML insight
print('\nRecommendation:')
print(f"- Focus on {best_segment['day']} {best_segment['time']} because it brings the highest bill revenue.")
print('- Use this segment for staffing and menu planning.')
print('- Offer targeted promotions or upsell items during the busiest times.')

print('\nHow ML can use this insight:')
print('- A model can learn day + time patterns to predict revenue. ')
print('- It can also use tip percentage to spot which slots give better customer value.')
print('- This helps the business plan staffing and menu offers more smartly.')
print('- In short, the model can turn the segment into a decision rule.')

Revenue summary by day and time:
    day    time  total_revenue  avg_tip_percentage  count
0  Thur   Lunch        1077.55           16.130074     61
1  Thur  Dinner          18.78           15.974441      1
2   Fri   Lunch          89.92           18.876489      7
3   Fri  Dinner         235.96           15.891611     12
4   Sat  Dinner        1778.40           15.315172     87
5   Sun  Dinner        1627.16           16.689729     76

Highest revenue segment:
day                         Sat
time                     Dinner
total_revenue            1778.4
avg_tip_percentage    15.315172
count                        87
Name: 4, dtype: object

Recommendation:
- Focus on Sat Dinner because it brings the highest bill revenue.
- Use this segment for staffing and menu planning.
- Offer targeted promotions or upsell items during the busiest times.

How ML can use this insight:
- A model can learn day + time patterns to predict revenue. 
- It can also use tip percentage to spot which slots give